# Generated by Django 4.2.11 on 2026-04-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediaassets',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='mediaassets',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
